version: '3.1'

services:
  backend:
    container_name: backend
    image: node:12
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -c 'yarn && yarn start'
    depends_on:
      - db
    links:
      - db
    networks:
      - nestnetwork

  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./db:/var/lib/postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - nestnetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - nestnetwork

networks:
  nestnetwork:
    driver: bridge
